version: '3'

services:

  web:
    restart: always
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
    - ./wp-cms-project/:/var/www/wp-cms-project/
    - ./conf/web.sh:/docker-entrypoint-initdb.d/web.sh
    - ./conf/start-web.sh:/docker-entrypoint-initdb.d/start-web.sh
    links:
      - db


  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - ./conf/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    - ./conf/setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh
    - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
