version: '3'

services:

  # web:
  #   image: nginx:latest
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
  #   volumes:
  #   - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
  #   - ./conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
  #   links:
  #       - php
  # php:
  #   image: php:7-fpm
  #   restart: always
  #   volumes:
  #   - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
  nginx:
    restart: always
    image: nginx:latest
    ports:
    - 80:80
    # volumes:
    # - ./conf/nginx.conf:/etc/nginx/conf.d/
    # - ./wp-cms-project/:/var/www/
    links:
    - php

  php:
    restart: always
    image: php:7.4-cli
    # links:
    # - db
    # volumes:
    # - ./wp-cms-project/:/var/www/

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
    - ./conf/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    - ./conf/setup-db.sh:/docker-entrypoint-initdb.d/setup-db.sh
    - ${DB_PATH_HOST}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
